spring:
  datasource:
    username: sa
    password: ye159357
    url: jdbc:sqlserver://localhost;database=test
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: UTF-8
    #     新版本不支持content-type: text/html，故新写法
    servlet:
      content-type: text/html
  mail:
    host: smtp.qq.com
    username: 1433068154@qq.com
    #设置密码,指的是smtp的授权码
    password: jtprijjzlhvhiijg
